http:
  address: "localhost"
  port: "8080"
postgres:
  connection:
    file_path: "./config/postgres.secret"
  host: ""
  port: 5432
  db: ""
  user: ""
  pass: ""
image:
  source:
    file_path: "./data/links.txt"
  upload_path: "./images/user-content"
  download_path: "./images/"