basePath: /api
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Image:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      download_date:
        type: string
      file_extension:
        type: string
      file_size:
        type: integer
      id:
        type: string
      local_name:
        type: string
      original_url:
        type: string
      path:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /images:
    get:
      description: images list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Image'
            type: array
      summary: HandleImagesList
      tags:
      - Images
  /images/{id}:
    get:
      description: downoald an image from list
      parameters:
      - description: image ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
      summary: HandleDownloadImage
      tags:
      - Images
  /images/download:
    get:
      description: download images from links file
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: HandleDownloadImages
      tags:
      - Images
  /images/upload:
    post:
      consumes:
      - multipart/form-data
      description: upload images
      parameters:
      - description: images
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: HandleImagesUpload
      tags:
      - Images
swagger: "2.0"
